prometheusAddr: ":9099"
services:
  - name: "test-service-1"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-1"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-2"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-2"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-3"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-3"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-4"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-4"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-5"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-5"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-6"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-6"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-7"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-7"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-8"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-8"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-9"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-9"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-10"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-10"
    suppressWhois: true
    timeout: 30s
