prometheusAddr: ":9099"
services:
  - name: "test-service-1"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-1"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-2"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-2"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-3"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-3"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-4"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-4"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-5"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-5"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-6"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-6"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-7"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-7"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-8"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-8"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-9"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-9"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-10"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-10"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-11"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-11"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-12"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-12"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-13"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-13"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-14"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-14"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-15"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-15"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-16"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-16"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-17"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-17"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-18"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-18"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-19"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-19"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-20"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-20"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-21"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-21"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-22"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-22"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-23"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-23"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-24"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-24"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-25"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-25"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-26"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-26"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-27"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-27"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-28"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-28"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-29"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-29"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-30"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-30"
    suppressWhois: true
    timeout: 30s
