services:
  - name: "test-service-1"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-1"
    prometheusAddr: ":9099"
    suppressWhois: true
    timeout: 30s
  - name: "test-service-2"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-2"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-3"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-3"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-4"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-4"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-5"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-5"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-6"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-6"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-7"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-7"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-8"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-8"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-9"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-9"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-10"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-10"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-11"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-11"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-12"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-12"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-13"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-13"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-14"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-14"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-15"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-15"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-16"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-16"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-17"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-17"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-18"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-18"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-19"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-19"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-20"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-20"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-21"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-21"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-22"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-22"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-23"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-23"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-24"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-24"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-25"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-25"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-26"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-26"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-27"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-27"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-28"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-28"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-29"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-29"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-30"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-30"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-31"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-31"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-32"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-32"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-33"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-33"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-34"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-34"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-35"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-35"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-36"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-36"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-37"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-37"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-38"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-38"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-39"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-39"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-40"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-40"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-41"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-41"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-42"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-42"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-43"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-43"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-44"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-44"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-45"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-45"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-46"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-46"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-47"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-47"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-48"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-48"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-49"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-49"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
  - name: "test-service-50"
    upstream: "http://localhost:8080"
    ephemeral: true
    funnel: false
    listenAddr: ":443"
    stateDir: "/tmp/tsnsrv-profile/service-50"
    prometheusAddr: ""
    suppressWhois: true
    timeout: 30s
